USE `schedule management`;

CREATE TABLE `users` (
	`id`	BIGINT	NOT NULL,
	`username`	VARCHAR(30)	NOT NULL,
	`email`	VARCHAR(50)	NOT NULL,
	`password`	VARCHAR(30)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`updated_at`	DATETIME	NOT NULL
);

CREATE TABLE `schedules` (
	`id`	BIGINT	NOT NULL,
	`title`	VARCHAR(50)	NOT NULL,
	`contents`	VARCHAR(200)	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`updated_at`	DATETIME	NOT NULL
);

CREATE TABLE `comments` (
	`id`	BIGINT	NOT NULL,
	`todo_id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`contents`	VARCHAR(100)	NOT NULL,
	`created_at`	DATETIME	NOT NULL,
	`updated_at`	DATETIME	NOT NULL
);

ALTER TABLE `users` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`id`
);

ALTER TABLE `users` MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `schedules` ADD CONSTRAINT `PK_SCHEDULES` PRIMARY KEY (
	`id`
);

ALTER TABLE `schedules` MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `comments` ADD CONSTRAINT `PK_COMMENTS` PRIMARY KEY (
	`id`
);

ALTER TABLE `comments` MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `schedules` ADD CONSTRAINT `FK_USERS` FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE `comments` ADD CONSTRAINT `FK_SCHEDULES` FOREIGN KEY (todo_id) REFERENCES schedules(id) ON DELETE CASCADE;